### ISSUE TITLE
Using csv files 

### ISSUE THREAD

**Issue by hkmztrk** [MarieOestreich/hCoCena#11]
Hello,

I am using the below script to load pre-saved DeSeq normalised count files for comparative co-expression analysis, but I keep getting the below error after read_data(...). Is there something I'm missing while using loaded datasets? Thanks! 

```
Error in base::exists(hcobject[["layers"]][[base::paste0("set", x)]][1]) : 
  invalid first argument

```

The script

```
# Load the datasets
data1 <- read.csv(file.path(...)))
data2 <- read.csv(file.path(...)))

# transpose to switch gene names to rows
data1 <- t(data1)
data2 <- t(data2)

# Define layers (no annotation files)
define_layers(list(
  Data1 = list(data = data1, annotation = NULL),
  Data2 = list(data = data2, annotation = NULL)
))

set_supp_files(
  Tf = "TFcat.txt"
)

read_data(
  sep_counts = NULL,
  sep_anno = NULL,
  gene_symbol_col = NULL,
  sample_col = NULL,
  count_has_rn = TRUE,
  anno_has_rn = FALSE
)

```

**Comment by MarieOestreich** [comment]
Hello!

It looks like the main issues lies in the call to ```define_layers```. 
If you look at the example given on how to call this in the `hcocena_main.Rmd`, it needs the following format for calling:

```
define_layers(list(RNA_Seq = c("data_batch_donor.txt", "annotation_seq.txt") ,
                   Array = c("data.txt", "annotation_array.txt")))
```

In your case this may be changed to 

```
define_layers(list(data1 = c("data1", "annotation_data1") ,
                   data2 = c("data2", "annotation_data2")))
```

This is also explained in more detail in the function documentation that you can access with ```?hcocena::define_layers```.

While this is likely the cause of your error, please also note that giving no annotation data (as you are currently doing by setting it to `NULL`) is not a valid option and is likely to cause unexpected behaviour or errors down the line. A minimal annotation is required, ideally including groups that the samples belong to (e.g., healthy/diseased).
If there is a very good reason why there is absolutely no annotation data, please reach out and we can think about including this as an option.


Best,
Marie

**Comment by hkmztrk** [comment]
Hi @MarieOestreich, thanks a lot for your fast response!

I included annotation files as you suggested,

```
define_layers(list(data1 = c("data1", "annotation_data1") ,
                               data2 = c("data2", "annotation_data2")))
```

The number of columns in data1/2 (samples) match with the number of rows (samples) in annotation_data1/2. The rows in the data1 correspond to the genes. However  I still get the initial error with the below read_data. 

```
Error in base::exists(hcobject[["layers"]][[base::paste0("set", x)]][1]) : 
  invalid first argument
```

```
read_data(
  sep_counts = NULL,
  sep_anno = NULL,
  gene_symbol_col = NULL,
  sample_col = NULL,
  count_has_rn = TRUE,
  anno_has_rn = TRUE
)

```

**Comment by MarieOestreich** [comment]
I see, can you tell me what exactly the output of `hcobject[["layers"]][[base::paste0("set", 1)]][1]` and `hcobject[["layers"]][[base::paste0("set", 2)]][1]` is? it should be data1 and data2.

**Comment by hkmztrk** [comment]
Yes, exactly, 

```
> hcobject[["layers"]][[base::paste0("set", 1)]][1] 
$data
[1] "data1"

> hcobject[["layers"]][[base::paste0("set", 2)]][1]
$data
[1] "data2"

```

**Comment by hkmztrk** [comment]
Hi @MarieOestreich,

Debugging this,

https://github.com/MarieOestreich/hCoCena/blob/0ffd2f2fa45d66d191f0dcc79959d82aacfec803/hCoCena-r-package/R/read_data.R#L24C2-L29C70

If I update the  lines as below, 

```
object_name <- as.character(hcobject[["layers"]][[base::paste0("set", x)]][1])

  if (base::exists(object_name)) {
  .....
  }


```
The error below disappears - would be great if you can confirm, thanks!

```
Error in base::exists(hcobject[["layers"]][[base::paste0("set", x)]][1]) : 
  invalid first argument
```

But later on, I get the following error, in the below line:
https://github.com/MarieOestreich/hCoCena/blob/0ffd2f2fa45d66d191f0dcc79959d82aacfec803/hCoCena-r-package/R/read_data.R#L31C5-L31C109

```
data[[base::paste0("set", x, "_counts")]]
Error in data[[base::paste0("set", x, "_counts")]] : 
  object of type 'closure' is not subsettable
```

**Comment by MarieOestreich** [comment]
Hi!
While that does seem to work (initially), the issues starts further up: The output of 
`
hcobject[["layers"]][[base::paste0("set", 1)]][1]
` for you is 


```
$data
[1] "data1"
```
However, it should just be (and is when i run it):

```
[1] "data1"
```

So there is something going wrong beforehand, that makes it necessary to do the additional call to `as.character()`. 
Unfortunately, it's very difficult to track down the problem entirely without a reproducible example. If your data is public, maybe you can send me the data and your markdown with which you get the error via e-mail. If it is not public data, maybe you can recreate the error with a public set and send me that.

Best,
Marie
