### ISSUE TITLE
Error in running run_expression_analysis_2()

### ISSUE THREAD

**Issue by jalilsharif** [MarieOestreich/hCoCena#2]
Hello,

I am using microarray test data, however, getting stuck after the ```plot_deg_dist()``` step, when running ```run_expression_analysis_2()```, I am getting the following error:

```
Error in `[.data.frame`(hcobject[["data"]][[paste0("set", x, "_anno")]], : undefined columns selected
Traceback:

1. run_expression_analysis_2()
2. run_expression_analysis_2_body(x = x, grouping_v = grouping_v, 
 .     plot_HM = plot_HM, method = method, additional_anno = additional_anno[[x]])
3. heatmap_network_genes(x = x, plot_HM = plot_HM, method = method, 
 .     additional_anno = additional_anno)
4. base::unique(hcobject[["data"]][[paste0("set", x, "_anno")]][, 
 .     i])
5. hcobject[["data"]][[paste0("set", x, "_anno")]][, i]
6. `[.data.frame`(hcobject[["data"]][[paste0("set", x, "_anno")]], 
 .     , i)
7. stop("undefined columns selected")
```

**Comment by MarieOestreich** [comment]
Hello!
to investigate this further, I would need to know
1) if you set the `additional_anno` parameter in the `run_expression_analysis_2` function or if you left it to default, and
2) if your "variable of interest" (`voi`) that you set in your global settings is indeed the name of a column of your annotation data table.

The iterator variable `i` in your error is either `voi` or whatever you may have set as  `additional_anno` (if anything). And one of these does not seem to exist as a column name in your annotation table.

Best,
Marie

**Comment by jalilsharif** [comment]
Hi Marie,
I am actually running the code from your vignette only having changed the file name. I imagine the VOI is the case/control parameter? I have amended my ```voi```.

So far I have not set any ```additional_anno```.

Would ```additional_anno``` use a specific column in the annotation file? And what alternative options are there for the parameters.

**Comment by MarieOestreich** [comment]
I ran the showcase both locally and on the [FASTGenomics ](https://beta.fastgenomics.org/analyses/detail-analysis-461f44b88207411f87669caccfb5ff8f)server, in both cases `run_expression_analysis_2` works fine. 
Where are you running the showcase? Or are you running it with your own data? If so, I need the following infromation:

1. How many datasets are you using?
2. Have you ensured that `voi` is a column name in all of your annotation tables?
3. Have you ensured, that you are reading the data and annotations correctly? Please also check out the [wiki ](https://github.com/MarieOestreich/hCoCena/wiki/General-Backgroud-Information)entry for info on the data formats.
4. I know it is not always possible to share bio data, but I could help you much better, if I had a reproducible example. If you could provide me with your markdowns and the data-/annotation-files you are using, that would be great.
5. Consider running the showcase example to get a feeling for the tool, how data should be read and the `hcobject` in general, if you have not done so already.

**Comment by jalilsharif** [comment]
Hi,

I am using only one dataset. Yes, the VOI has been amended. It would be easier to send a subset data via email. Is the @dzne.de your current email address?
