### ISSUE TITLE
requires remotes

### ISSUE THREAD

**Issue by dansteiert** [MarieOestreich/hCoCena#5]
I tried to install hCoCena but got promted that remotes is not present:
`Error in loadNamespace(x) : there is no package called ‘devtools’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
`

Since you already have an installer for dependencies, this would make an important addition for ease of installation - even though it is not a "real" issue to install remotes myself 

Cheers!

**Comment by MarieOestreich** [comment]
Thanks for pointing that out!
I made the corresponding changes.

Best,
Marie
